### ISSUE TITLE
DataStream missing

### ISSUE THREAD

**Issue by aaronjbrown** [open-dis/open-dis-cpp#1]
When compiling, I get "fatal error: 'DIS/DataStream.h' file not found" and if I "touch DIS/DataStream.h" I get multiple "error: unknown type name 'DataStream'"

**Comment by aaronjbrown** [comment]
cd open-dis-cpp/Compile/gnu.linux
make
==== Building DIS ====
make[1]: *** No rule to make target `../../cpp/DIS/DataStream.h', needed by `obj_gnu_DIS_debug/AcknowledgePdu.o'.  Stop.
make: *** [DIS] Error 2

touch ../../cpp/DIS/DataStrem.h
make
==== Building DIS ====
AcknowledgePdu.cpp
In file included from ../../cpp/DIS/AcknowledgePdu.cpp:1:
In file included from ../../cpp/DIS/AcknowledgePdu.h:4:
In file included from ../../cpp/DIS/SimulationManagementFamilyPdu.h:4:
../../cpp/DIS/EntityID.h:33:26: error: unknown type name 'DataStream'
    virtual void marshal(DataStream& dataStream) const;
                         ^
../../cpp/DIS/EntityID.h:34:28: error: unknown type name 'DataStream'
    virtual void unmarshal(DataStream& dataStream);
                           ^
In file included from ../../cpp/DIS/AcknowledgePdu.cpp:1:
In file included from ../../cpp/DIS/AcknowledgePdu.h:4:
In file included from ../../cpp/DIS/SimulationManagementFamilyPdu.h:6:
../../cpp/DIS/Pdu.h:45:26: error: unknown type name 'DataStream'
    virtual void marshal(DataStream& dataStream) const;
                         ^
../../cpp/DIS/Pdu.h:46:28: error: unknown type name 'DataStream'
    virtual void unmarshal(DataStream& dataStream);
                           ^
In file included from ../../cpp/DIS/AcknowledgePdu.cpp:1:
In file included from ../../cpp/DIS/AcknowledgePdu.h:4:
../../cpp/DIS/SimulationManagementFamilyPdu.h:33:26: error: unknown type name 'DataStream'
    virtual void marshal(DataStream& dataStream) const;
                         ^
../../cpp/DIS/SimulationManagementFamilyPdu.h:34:28: error: unknown type name 'DataStream'
    virtual void unmarshal(DataStream& dataStream);
                           ^
In file included from ../../cpp/DIS/AcknowledgePdu.cpp:1:
../../cpp/DIS/AcknowledgePdu.h:34:26: error: unknown type name 'DataStream'
    virtual void marshal(DataStream& dataStream) const;
                         ^
../../cpp/DIS/AcknowledgePdu.h:35:28: error: unknown type name 'DataStream'
    virtual void unmarshal(DataStream& dataStream);
                           ^
../../cpp/DIS/AcknowledgePdu.cpp:48:30: error: unknown type name 'DataStream'
void AcknowledgePdu::marshal(DataStream& dataStream) const
                             ^
../../cpp/DIS/AcknowledgePdu.cpp:56:32: error: unknown type name 'DataStream'
void AcknowledgePdu::unmarshal(DataStream& dataStream)
                               ^
10 errors generated.
make[1]: *** [obj_gnu_DIS_debug/AcknowledgePdu.o] Error 1
make: *** [DIS] Error 2

**Comment by aaronjbrown** [comment]
From open-dis-cpp/cpp/DIS/ I ran:
ln -s ../../CppUtils/DIS/DataStream.h 
ln -s ../../CppUtils/DIS/DataStream.cpp

then from open-dis-cpp/Compile/gnu.linux I could run make, with the result:
...
VariableDatum.cpp
Vector3Double.cpp
Vector3Float.cpp
VectoringNozzleSystemData.cpp
WarfareFamilyPdu.cpp
Conversion.cpp
DataStream.cpp
IncomingMessage.cpp
PacketFactory.cpp
PDUBank.cpp
../../CppUtils/DIS/PDUBank.cpp:51:11: warning: enumeration value 'PDU_OTHER' not handled in switch [-Wswitch]
   switch(pdu_type)
          ^
1 warning generated.
StreamUtils.cpp
Linking DIS
==== Building UnitTest_DIS ====
DataStreamTests.cpp
../../UnitTestDIS/DataStreamTests.cpp:5:10: fatal error: 'cppunit/extensions/HelperMacros.h' file not found
#include <cppunit/extensions/HelperMacros.h>
         ^
1 error generated.
make[1]: *** [obj_gnu_UnitTest_DIS_debug/DataStreamTests.o] Error 1
make: *** [UnitTest_DIS] Error 2



Now I have missing references to nl.h, is it possible to get a list of dependencies before compiling/developing? Thanks!

**Comment by leif81** [comment]
Thanks @aaronjbrown . I personally haven't built the c++ library in a while so I'm not sure how much I can help off the top of my head. But this is a good reminder we should setup a TravisCI job for his repository, similar to what we have for the open-dis-java library, to demonstrate it compiling.

**Comment by leif81** [comment]
@aaronjbrown Once the `travis` branch is merged in I'll ask you retry your build, I think it'll resolve your problems.

**Comment by mcgredonps** [comment]
Thanks Leif, my current sickness very much limits my ability to do stuff that
needs to be done.

On Jul 20, 2017, at 10:02 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


@aaronjbrown<https://github.com/aaronjbrown> Once the travis branch is merged in I'll ask you retry your build, I think it'll resolve your problems.

**Comment by leif81** [comment]
@aaronjbrown The PR auto-closed this issue when it was merged. But feel free to reopen it if it didn't fix your issue.

**Comment by aaronjbrown** [comment]
Thank you Leif! I pulled the latest and it compiles without issues on Mac, I haven't retested on my Ubuntu but the TravisCI is Ubuntu :) Thanks for your effort, and for looking at it so quick!
