### ISSUE TITLE
Signal PDU misinterpretation

### ISSUE THREAD

**Issue by dilavni** [open-dis/open-dis-cpp#10]
https://github.com/open-dis/open-dis-cpp/blob/86e8c24edfd0132ef3f4e38c0f17067781e6c892/cpp/DIS/SignalPdu.cpp#L98-L114

There are multiple errors here. First of all "_dataLength" in interpreted incorrectly as bytes, when it's in fact bits / or a constant value when using the encoding scheme for database index.

From the standard: (emphasis added): "Data Length - This field shall specify the number of *bits* of digital voice audio or digital data being sent in this Signal PDU. This field shall be represented by a 16-bit unsigned integer. If the Encoding Class is database index, the Data Length field shall contain the value 96."

Also: "Data - This field shall specify the audio or digital data conveyed by the radio transmission. The interpretation of the Data field depends on the value of the Encoding Scheme (see 5.4.8.2(d)) and TDL Type (see 5.4.8.2(e)) fields."

How does error manifest itself? Basically you're trying to read/unmarshal too much data (8 times). If you have defined large enough buffer for DataStream, this problem goes undetected, but the extra data will be trash (just the contents of the read buffer). If you have a buffer sized according to the incoming PDU, this will cause undefined behaviour. Essentially DataStream will index over it's buffer.

There are similar problems in marshal. Data length f.e. will be encoded incorrectly.

**Comment by leif81** [comment]
Thank you @dilavni Nice catch!

If I recall, a similar fix was needed to the `open-dis-java` library. There's a trend happening here! Here's that patch if it helps confirm your thoughts.

https://github.com/open-dis/open-dis-java/commit/9b20d4d0f0992157dcd4a0ecf1e8ae62717e984e#diff-5d13a4f131b76879516bb03083caae46

If you are interested in submitting a PR it would be welcomed!

**Comment by dilavni** [comment]
I wonder if the data is always aligned to 8-bits (_dataLength % 8 always zero). If it cannot assumed to be, there might be a problem in the design, as the user is able to manipulate the data field directly and the "data length" field is automatically calculated from the size of data (which is just bytes)

**Comment by leif81** [comment]
Hmm yes, I remember this being confusing in the `open-dis-java` library too. Most of the code was auto generated so that's why in some areas it's a bit raw.

If I recall, the `setData`, `getData`, `setDataLength`, `getDataLength` should be the data *without* the zero'd padding.  And the library should be padding the `_data` field for free as part of the `marshall` and `unmarshall calls. But, I don't see where that's happening, I think that's missing here.



The library could (and maybe should) hide details of the wire format, like the padding here.

**Comment by leif81** [comment]
I don't think I answered your question yet. The `_data` field is made of `OneByteChunk`'s so ya it'll be aligned to 8-bits.

**Comment by dilavni** [comment]
In the current implementation yes, but what does the standard say? If the data length field is defined in bits, it would stand to reason that it doesn't necessarily align to a byte boundary (talking of the designated data of course; the PDU itself will always align). If the standard says that it's in bits for no real reason and the data length field % 8 is always zero then the fix is quick and easy.

If it does not, there's a problem in the implementation. The direct access to the data field bytes must be hidden and set member defined in terms of bit length like this "setData(const char *data, std::size_t bitLength);". Direct access cannot be given, because counting the data length from the array size looses the bitsize and forces alignment when it might not be appropriate.

The way it is incorrectly implemented now, there is a lucky side to it: the size is interpreted as bytes and therefore the return "data length size" is always correct when dealing with UNMARSHALLED pdu (not with marshalled). The implementation simply unmarshals too much, but it wont break anything if the buffer is large enough.

Do you follow or agree with my reasoning? I'm very busy at work atm, so it might be awhile before I get back to it. Perhaps next week.

**Comment by leif81** [comment]
Ok, I see. In practice I've never encountered data that wasn't 8-bit aligned, the spec doesn't say it *must* be, so you're probably right. Yes, `getData` would return back too much data and the user will have to trim it based on the length field.

Here's what the spec says:

On length:

> Data Length. This field specifies the length of the Data field in bits. If the Encoding Class is
> Database Index (3), the Data Length field shall contain the value 96.


On data:

> Data. The length of the valid data contained in this field shall be the value of the Data Length field.
> The Data field shall be zero-padded to comply with the overall PDU length requirements (see 6.3.2).
> The interpretation of this field depends on the value of the TDL Type field and of the Encoding
> Class field of the Encoding Scheme record as follows:
> 1) If the Encoding Class is Encoded Audio (0), the Data field shall be interpreted as containing
> audio information digitally encoded as specified by the encoding type.
> 2) If the Encoding Class is Raw Binary Data (1), the format of the data shall be specified by the
> TDL Type field.
> 3) If the Encoding Class is Application-Specific Data (2), the first 32 bits of the Data field shall
> specify a User Protocol identification number (see [UID 177]). The remainder of the Data field
> shall be interpreted as specified by the user protocol.
> 4) If the Encoding Class is Database Index (3), the Data field shall be composed of three fields:
> i) A 32-bit unsigned integer (data octets 0 to 3) index into a predefined database of
> prerecorded data.
> ii) A 32-bit unsigned integer (data octets 4 to 7) specifying the offset in milliseconds from the
> start of the index data.
> iii) A 32-bit unsigned integer (data octets 8 to

And here's what the 6.3.2 reference says:

> 6.3.2 Alignment
> Each field in a PDU starts at an offset from the beginning of the PDU that is a multiple of its size. Each
> record in a PDU shall start at an offset that is a multiple of the size of the largest field in the record. If the
> PDU contains a 64-bit field, then the length of the PDU shall be a multiple of 64 bits. Otherwise, the length
> of the PDU shall be a multiple of 32 bits. Padding bits shall be used to achieve these offsets
