### ISSUE TITLE
Can't be compile 

### ISSUE THREAD

**Issue by EricaAngle** [open-dis/open-dis-cpp#11]
it seems some files are missing. 
eg: DIS/msLibMacro.h can't be found. 
      DIS/SyntheticEnvironmentFamilyPdu.h

**Comment by leif81** [comment]
Hi @EricaAngle thank you for the report. 

Could you describe how you are trying to compile? 

There is an example for how to compile in the project readme, have you tried that?

**Comment by leif81** [comment]
@EricaAngle I'm going to close this one. Feel free to reopen if it's still affecting you.
