### ISSUE TITLE
Unclear software structure

### ISSUE THREAD

**Issue by plata** [open-dis/open-dis-cpp#12]
To me, the structure of the software is a bit unclear:

- The files in DIS7 are including `<DIS/...>`. This is probably not intended.
- The directories in `cpp` and `CppUtils` are both called `DIS`. What will happen if a file with the same name exists in both directories (i.e. `#include <DIS/...>` might easily include the wrong file)?

As a result of this: How should, in your opinion, open-dis-cpp be installed for development on a Linux system?

In my opinion, these issues could be solved by:
- Use CMake for building
- Use CPack to build RPM/ZIP etc.
- Build 3 packages: utils, dis6, dis7 (install header files to: /usr/include/open-dis/utils, /usr/include/open-dis/dis6, /usr/include/open-dis/dis7)
- Restructure directories such that above package structure is represented (→ `#include <DIS/...>` becomes `#include <open-dis/dis6/...>`)

**Comment by leif81** [comment]
Thank you for the report @plata 

You're totally right. Yes, I think it'd be a good idea to move things around a bit to start with.

Maybe something like this:

`cppUtils/DIS` -> `src/utils`
`cpp/DIS` -> `src/dis6`
`cpp/DIS7` -> `src/dis7`
`UnitTestDIS` -> `test`
`Example` -> `examples`

Would you like to submit a PR for that?

**Comment by leif81** [comment]
Should we keep this one open or do those changes help enough to close?

**Comment by plata** [comment]
Packages would still be nice but I can open a separate issue for that.
