### ISSUE TITLE
Rework PDUBank handling

### ISSUE THREAD

**Issue by plata** [open-dis/open-dis-cpp#17]
Currently, the PDUBank (and thus the available PDUs) is hardcoded in https://github.com/open-dis/open-dis-cpp/blob/05aa32c59397b7c889a6b603a6327c69ae0b4420/src/utils/IncomingMessage.cpp#L46

As a consequence, it is not possible to use a different PDUBank without changing the code. However, this is required e.g. to use DIS 7 PDUs.

I suggest to implement the PDUBank handling in a similar way to the PacketProcessors, i.e.
- make a PDUBank base class with a method `Pdu* GetStaticPDU(const DataStream&) const`
- register the desired PDUBank implementation similar to `IncomingMessage::AddProcessor`

This would also help reducing the cyclic dependencies between the PDUs and the utils.

**Comment by leif81** [comment]
@phoppermann was this fixed by #32 ?

**Comment by phoppermann** [comment]
Yes.
