### ISSUE TITLE
Error while building DIS7 Win10 - mingw730_64

### ISSUE THREAD

**Issue by manu-SSG** [open-dis/open-dis-cpp#25]
Hello,

I'm trying to build library in DIS7 on Win10 with mingw730_64 and have the following error : 

> src/dis7/VariableDatum.cpp:61:35: error: '_variableDatums' was not declared in this scope

Indeed, the variable `_variableDatums` is not declared in the header file and not initialize in the constructor.

After adding it in both file, i have an other error : 

> src/dis7/VariableDatum.cpp:66:9: error: 'EightByteChunk' was not declared in this scope

The header `variableDatum.h` don't include ` 'EightByteChunk' `

After adding it, I have the following error : 

> src/dis7/VariableDatum.cpp:66:47: error: conversion from 'const value_type {aka const char}' to non-scalar type 'DIS::EightByteChunk' requested
         EightByteChunk x = _variableDatums[idx];

Do you have any  idea, how to fix it ? 

I suggest you to add an appVeyor for your continuous integration indeed, you only test it on Linux with DIS6.

I have no problem with the DIS6
Thanks for your work !

**Comment by leif81** [comment]
Thank you for the report @manu-SSG 

I'll be honest, for my use case I only use DIS6, so I'm not surprised you found an issue with the DIS7 code.

I like your suggestion to setup appVeyor, I will try to look into that in the near future.

**Comment by PeterSassaman** [comment]
I believe

#include <dis7/EightByteChunk.h>

std::vector<EightByteChunk> _variableDatums;

can be added to VariableDatum.h to solve that issue.

I think the lines referencing resupplycancelpdu also have to be removed from PDUBank.cpp

The other thing is that all the dis6/ have to be changed to dis7/ in the utils.  Is there any way to have all of these changes produced by the premake file?

**Comment by rodneyp290** [comment]
I was looking into this in relation to #38 to see if it was related, but I believe this was resolved in commit d51455fd, merged in #31.

**Comment by leif81** [comment]
Great. Thank-you @rodneyp290 for identifying that. Lets close this then.
