### ISSUE TITLE
Linux build instructions fail

### ISSUE THREAD

**Issue by joe-sonrichard** [open-dis/open-dis-cpp#28]
### DESCRIBE THE BUG
Linux build instructions fail.

### STEPS TO REPRODUCE
Steps to reproduce the behaviour:
1. Clone the repo.
2. Put premake5 in a folder included in $PATH environment variable.
3. Run `premake5 gmake` in repo root directory.
4. Run `make config=release` and observe error.

### EXPECTED BEHAVIOUR
Make command succeeds.

### ACTUAL BEHAVIOUR
Make fails fatally due to undocumented dependency in example code.

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/49208786/64988484-87b6a280-d899-11e9-9612-945d6d1fb82b.png)

### ENVIRONMENT
 - **OS:** Pop_OS! 18.04

**Comment by leif81** [comment]
@joe-sonrichard you're right the SDL dependency should be documented in the readme. Until that's done take a look a the travis config for how we setup the build environment.

https://github.com/open-dis/open-dis-cpp/blob/master/.travis.yml
