### ISSUE TITLE
Replace HawkNL in examples

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-cpp#3]
I'm not terribly familiar with the HawkNL library, but from what I can tell it used to be very popular, but looks to be no longer maintained and fallen out of popularity. So to get the `Examples` code compiling we may want to pick a replacement library.

I don't do much C++ dev these days, so I'm out of the loop in terms of what people actually use, but a couple potential replacement options that may be suitable are Boost (Asio) and SDL2 (SDL_net).

http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio.html
https://www.libsdl.org/projects/SDL_net/

**Comment by BenMueller** [comment]
This has been a particular point of annoyance recently- ripping HawkNL out of old projects is rather fun I can tell you :wink: that said it would seem to me the primary advantage of HawkNL was the simple bidirectional (capable of sending and receiving on the same socket) nature of the library. Any good reasons we can't just use the standard sockets for basic functionality?

I've made fork to experiment with some replacements, can't make any promises as to when but at some point I'll update with progress. Until then, feel free to make any suggestions.

Cheers,
Ben

**Comment by leif81** [comment]
Hi @BenMueller 

Using standard sockets seems like a great idea. That way we don't give impression HawkNL (or some other complex third party networking library) is required if it's not. Please feel free to submit a pull request with standard sockets.

**Comment by leif81** [comment]
@benmueller did you see PR #22 yet?

**Comment by leif81** [comment]
@BenMueller are you related to PR #22 that came in this week? It's a replacement of HawkNL with SDL_Net library. It looks pretty solid to me and it would satisfy this issue. I'm leaning towards merging that, if you have further improvements please feel free to create another PR.
