### ISSUE TITLE
Change settings to merge PRs with squash and merge

### ISSUE THREAD

**Issue by phoppermann** [open-dis/open-dis-cpp#34]
Avoid that PR merges clutter the [commit history](https://github.com/open-dis/open-dis-cpp/commits/master) (e.g. the merge of #31).

see https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests

**Comment by leif81** [comment]
We have the "allow squash merging" enabled as an option on PR's.

Obviously I don't use it often when merging! I do appreciate a clean history a lot, and I used to feel very strongly about it, but I've shifted slightly and now I also appreciate the detailed history of the unsquashed merge.

Best of both worlds I think would be if git tooling was better and enabled us to click on the merge commit in history and see the combined diff as if it were a squashed commit. We get that on github by clicking on the link back to the PR, but it would be nice if native git tooling supported that too.

Feel free to reopen if I missed the point. Cheers.

**Comment by phoppermann** [comment]
It was just a proposal. Like I said, I prefer the clean history over the detailed history.

In the end it's of course your decision what you like to see in your repository :wink:.
