### ISSUE TITLE
Link to HawkNL library not working in Examples

### ISSUE THREAD

**Issue by giorossi91** [open-dis/open-dis-cpp#4]
The link to the **HawkNL** library in the CPP example ([http://www.hawksoft.com/hawknl/](http://www.hawksoft.com/hawknl/)) returns `404` HTTP error code.

**Comment by leif81** [comment]
Thank you for the report @giorossi91 

#3 is a similar issue so I'm going to close this one. Please feel free to submit a pull request for it.
