### ISSUE TITLE
building and running the tests

### ISSUE THREAD

**Issue by kurtsansom** [open-dis/open-dis-cpp#46]
The test directory has some test code in it, but the instructions are very vague.
it references cppunit, and set the path for cppunit.

It doesn't appear there are any build instructions. 

how how would it be to add this to the cmake and enable a test variable?

is anyone using using the test directory?

**Comment by leif81** [comment]
@kurtsansom the cppunit tests folder was contributed to the project by the original maintainer years ago. travisci and cmake were added afterwards to the project and were not setup with the cppunit tests yet. 

This library is 100% dependent on contributions from users. So any kind of contributions in the form of a pull request to setup the cppunit tests, with cmake and travis would be very welcome.
