### ISSUE TITLE
EntityStatePdu wrong marshalled size calculation (number of articulation parameters)

### ISSUE THREAD

**Issue by DPD85** [open-dis/open-dis-cpp#48]
Inside the implementation of EntityStatePdu I discovered that the marshalled size of the PDU is calculated assuming to be present always only one articulation parameter. This is true for DIS6 and DIS7.

```int EntityStatePdu::getMarshalledSize() const
{
   int marshalSize = 0;

   marshalSize = EntityInformationFamilyPdu::getMarshalledSize();
   marshalSize = marshalSize + _entityID.getMarshalledSize();  // _entityID
   marshalSize = marshalSize + 1;  // _forceId
   marshalSize = marshalSize + 1;  // _numberOfArticulationParameters
   marshalSize = marshalSize + _entityType.getMarshalledSize();  // _entityType
   marshalSize = marshalSize + _alternativeEntityType.getMarshalledSize();  // _alternativeEntityType
   marshalSize = marshalSize + _entityLinearVelocity.getMarshalledSize();  // _entityLinearVelocity
   marshalSize = marshalSize + _entityLocation.getMarshalledSize();  // _entityLocation
   marshalSize = marshalSize + _entityOrientation.getMarshalledSize();  // _entityOrientation
   marshalSize = marshalSize + 4;  // _entityAppearance
   marshalSize = marshalSize + _deadReckoningParameters.getMarshalledSize();  // _deadReckoningParameters
   marshalSize = marshalSize + _marking.getMarshalledSize();  // _marking
   marshalSize = marshalSize + 4;  // _capabilities

   for(unsigned long long idx=0; idx < _articulationParameters.size(); idx++)
   {
        ArticulationParameter listElement = _articulationParameters[idx];
        marshalSize = marshalSize + listElement.getMarshalledSize();
    }

    return marshalSize;
}
```

As is possible to see the number of articulation parameters is stubbed to one when instead it should be _articulationParameters.size().

**Comment by leif81** [comment]
Thank-you for this report @DPD85 . Would you be interested in submitting a PR to fix this?

**Comment by DPD85** [comment]
@leif81 I did it.

**Comment by DPD85** [comment]
@leif81 
It is necessary to revert this because

> marshalSize = marshalSize + _articulationParameters.size();  // _numberOfArticulationParameters

this is the size of the variable containing the number of articulation parameters and not the number of articulation parameters.
So if you marshal the PDU and compare the size of the buffer with the marshalled size then you will find a difference of 1 byte.

Sorry for the mistake! :-(

**Comment by leif81** [comment]
Ok thanks for heads up. Can you submit a pull request? I'll merge it when it comes in.

**Comment by leif81** [comment]
Or did you want the whole original pull request reverted?

**Comment by DPD85** [comment]
You can revert the entire original pull request

**Comment by leif81** [comment]
Thank-you @DPD85 , the revert is don now.
