### ISSUE TITLE
Variable Datum in DIS7

### ISSUE THREAD

**Issue by aprowe** [open-dis/open-dis-cpp#6]
Hello, 

In DIS7/VariableDatum.h, variableDatumBits is an `unsigned int` instead of `  std::vector<EightByteChunk> `

```
/** Variable datum. This can be any number of bits long, depending on the datum. */
  unsigned int _variableDatumBits; 
```

it looks like DIS7/VariableDatium.cpp uses DIS/VariableDatum.h, so looks like this code isn't event compiling. 

Thanks for your work!

**Comment by aprowe** [comment]
Also, while I have your attention whats the difference between DIS and DIS7?

**Comment by leif81** [comment]
Thanks @aprowe 

DIS is v6.

**Comment by leif81** [comment]
The build (`premake5.lua` file) is only compiling DIS (v6) by the looks of it. Unless you really want DIS v7, I would suggest just using v6, very few things use DIS v7 from my knowledge.

Ya that certainly looks like a typo to me, I don't see why the `DIS7/VariableDatium.cpp` wouldn't include `DIS7/VariableDatium.h`.

Do you want to submit a pull request for these things?

**Comment by leif81** [comment]
I think you found a larger issue. It appears many (or all?) of the DIS7 `.cpp` files point to the DIS folder for the `.h`. I suspect that's not right!

**Comment by leif81** [comment]
Something else I noticed that will likely be problematic is that the namespace for both the DIS and DIS7 folders are both "DIS", so things presumably would collide if we built them both into the same library.

Short term...I'll stick to my earlier suggestion to just use the DIS (6) implementation unless you desparately need DIS7 support, which is rare.

**Comment by aprowe** [comment]
Thanks for the responses, @leif81 

I found another problem- VariableDatum is reporting and serializing the number of EightByteChunks as it's length; i.e. two chunks is giving a length of 2, when according to the DIS protocol, it should be the number of bits. changing it to (num of eight byte chunks) * 8 * 8 gave the correct number of bits.

It didn't come up before, because it's working as implemented, but just doesn't adhere to the protocol.

I can make a pull request to fix this.

**Comment by leif81** [comment]
That'd be great, thank you @aprowe

**Comment by DaveL1292** [comment]
So is the issue with the VariableDatum resolved for dis7?
I still get a compile error that _variableDatums is not defined.

If I comment out all references to _variableDatums it will compile, but not link.... Not sure if I am missing somehtign else as well. I downloaded this 3 days ago and I am building it as x64 / Debug with VS2107.
