### ISSUE TITLE
Add open-dis-cpp to vcpkg

### ISSUE THREAD

**Issue by leonardooyama** [open-dis/open-dis-cpp#63]
What about including the port of open-dis-cpp tp vcpkg (https://github.com/microsoft/vcpkg#contributing)?

**Comment by leif81** [comment]
@leonardooyama I like this idea a lot but I don't yet know how much effort it'll be. Have you experience?

**Comment by leonardooyama** [comment]
Will learn about it.

**Comment by wadehunk** [comment]
I'm also interested in getting open-dis submitted to the Conan Center repository as well. I've got contributor permissions there and hope to get it integrated, but they require access to immutable source code packages. Could also look into vcpkg. Both would require creating a tagged release version on github to reference. See #75 . I have my own selfish purposes for this, but I think this would also open up potential wider use of open-dis.

**Comment by leif81** [comment]
@wadehunk I think this is a good idea. Is there anything special we need to do to do to the code base to prepare or is all we need a tagged release tarball? e.g. open-dis-cpp-1.0.0.tar.gz

**Comment by wadehunk** [comment]
@leif81 I've got a draft conan recipe that I can get submitted to the Conan Center repository, just need a tagged release. I'm less familiar with vcpkg, but I'm pretty sure it's a very similar process.

**Comment by leonardooyama** [comment]
Nop. I am only a OpenDIS and vcpkg user. I don't have much expertise in
CMAKE, which I believe is required for including a project in vcpkg.

**Comment by wadehunk** [comment]
Looked into creating a vcpkg port and it actually looks easier than conan. I will get one submitted as soon as there is a release.

**Comment by leif81** [comment]
I've created a separate issue to track publishing a conan package #77 

Am thinking that based on interest we can publish as a vcpkg or conan or both.

**Comment by wadehunk** [comment]
VCPkg PR: microsoft/vcpkg#29472
Once a release is tagged, can update and mark as ready.

**Comment by leif81** [comment]
@wadehunk I've tagged a v1.0.0 release

**Comment by leif81** [comment]
Woops I guess we'll need a 1.0.1 release.  ref #78. No biggie, give me a few minutes.

**Comment by leif81** [comment]
@wadehunk I've tagged a new release v1.0.1 that includes #78 . Over to you

**Comment by leonardooyama** [comment]
These are great news! Thank you so much!

**Comment by wadehunk** [comment]
PR microsoft/vcpkg#29472 has been merged! open-diss-cpp should be available via VCPkg as soon as it propagates through the CDN.

**Comment by leif81** [comment]
@wadehunk I could be looking in the wrong spot but have you seen the open-dis-cpp appear in vcpkg yet? When I query for it I don't see it yet. https://vcpkg.io/en/packages.html

**Comment by wadehunk** [comment]
@leif81 That index must not get updated often. Seems like it has listed 2022 total packages for a while now. The latest release notes open-dis-cpp as 1 of 47 new ports added: https://github.com/microsoft/vcpkg/releases/tag/2023.02.24

Maybe it will eventually show up there.

**Comment by leonardooyama** [comment]
If you clone the vcpkg project to your PC, you  have to run the bootstrap-vcpkg.bat using cmd or PowerShell. After this, you just have to run "vcpkg install open-dis-cpp:x64-windows". If you want to export the library to use into other environments, like I do with Qt Creator, just run "vcpkg export open-dis-cpp --zip". It will generate a zip file with your library compiled. The good thing about this is that you can easily generate your binaries with your compiler version. Let's say, you can be using either VS 2019 or VS 2022. You will get all binaries and dependencies ready to use. Other good libraries are in vcpkg as well, such as GDAL and GeographicLib (good library to convert to/from MGRS and lat/long and calculate geodesic lines).

**Comment by leonardooyama** [comment]
Open-Dis-Cpp is officially into vcpkg. Thanks!
