### ISSUE TITLE
IFFPdu bug on SystemIdentifier.h and SystemIdentifier.cpp

### ISSUE THREAD

**Issue by CarlosSprekelsen** [open-dis/open-dis-cpp#65]
I tried to implement the IFFPdu, but it failed to form a correct stream. I managed to identify the issue with the code. 
Under SystemIdentifier _systemMode shall be 8-bit, but it is defined as a unsigned short (16bit). 
The correct declaration should be : 

`unsigned char _systemMode; `

and corresponding gets and sets should change accordingly.

**Comment by leif81** [comment]
Thanks for the report @CarlosSprekelsen 

Would you like to submit a pull request with the fix? I can review and merge.
