### ISSUE TITLE
Issues building with open dis

### ISSUE THREAD

**Issue by mgibson2020** [open-dis/open-dis-cpp#7]
Hi there. My team and I are trying to use the examples given to build our own project but every time we try to implement anything within open like the DIS::IncomingMessages we get the following error:

"unresolved external symbol "__declspec(dllimport) ..." 

We have all the header files in our project, linked OpenDIS.lib and copied OpenDIS.dll to the project folder. Are we missing something or is this a known issue when trying to build inside a project?

**Comment by leif81** [comment]
If you have the headers and `.lib`, you shouldn't need the `.dll`.

**Comment by leif81** [comment]
@mgibson2020 did this suggestion work out for you?

**Comment by leif81** [comment]
@mgibson2020 I'm going to close this because we didn't get a response so I'm going to assume it worked. Feel free to reopen if you're still having issues.
