### ISSUE TITLE
passing std::vector<ArticulatedPart> by ref in EntityStatePdu setter function.

### ISSUE THREAD

**Issue by shadow88s** [open-dis/open-dis-cpp#70]
I'm having trouble passing a std::vector from a QT project to the setter function by reference. compiling the projects with C++14 and MSVC 2019 Debug mode. 

These are the functions I'm trying to use from the EntityStatePdu class:
    std::vector<ArticulationParameter>& getArticulationParameters(); 
    const std::vector<ArticulationParameter>& getArticulationParameters() const; 
    void setArticulationParameters(const std::vector<ArticulationParameter>&    pX);

When I pass a std::vector<ArticulationParameter> variable from QT, it seems to have a different binary layout on MSVC. 
Could it possibly be a compiler option that I have to match with OpenDIS in order to pass the same std::vector?

**Comment by rodneyp290** [comment]
If your using a different compiler in your Qt project, there may be a possibility is in compatible :shrug: 
Assuming you're using Qt Creator for the Qt project, you should also be able to use the CMake to compile OpenDIS in Qt Creator, thus using the same compiler. 

However, it's a bit unclear what issue your describing without any error message, or code context.

**Comment by shadow88s** [comment]
@rodneyp290 . Thank you! User Error, I was trying to use premake5 instead of CMake to configure/generate the make file and build/complie the MSVC Solution file.  Using CMake with the debug, x64 configuration matching my project fixed it.
