### ISSUE TITLE
Create release version

### ISSUE THREAD

**Issue by wadehunk** [open-dis/open-dis-cpp#75]
Would be nice to have a versioned release of open-dis-cpp to support configuration management use cases for users of the library. Would recommend using [semantic versioning](https://semver.org) to capture API breakages.

**Comment by leif81** [comment]
Agree, this is a good idea. We use semantic versioning on open-dis-java. Perhaps once we get #74 merged we'll tag a 1.0.0 release and then iterate releases from then onwards.

**Comment by leif81** [comment]
Actually perhaps we do #18 as well because it's potentially a breaking change right away.

**Comment by wadehunk** [comment]
I've got a draft for #18 and can submit a PR for it once #74 is completed.
