### ISSUE TITLE
Add open-dis-cpp to Conan repository

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-cpp#77]
To make it easier for developers to use open-dis-cpp in their projects, it would be nice to add the library to the Conan repository.

https://conan.io

/cc @wadehunk

**Comment by wadehunk** [comment]
Conan Center PR: conan-io/conan-center-index#15776
Once a release is tagged, can update and mark as ready.

**Comment by wadehunk** [comment]
conan-io/conan-center-index#15776 finally merged. It’s good to go.
