### ISSUE TITLE
segmentation fault in VariableDatum::unmarshall

### ISSUE THREAD

**Issue by dilavni** [open-dis/open-dis-cpp#8]
https://github.com/open-dis/open-dis-cpp/blob/64200a2bf7de4041a050b2612bcd5502a836742a/cpp/DIS/VariableDatum.cpp#L113

There is no check for if _arrayLength is in fact larger than STATIC_ARRAY_LENGTH. If you get a VariableDatum larger than the allowed static array length, this blows in your face.

Thank you for your work!

**Comment by leif81** [comment]
Thank you @dilavni . 

Would you like to submit a pull-request with a proposed fix?

**Comment by dilavni** [comment]
Well I fixed it temporarily locally according to RAII by throwing an exception, which will be dealt by my factory (thrown to trash, I don't want a half constructed PDU anyway), but I don't know how you'd like to have this fixed in the library.

I see there being basically three options: 
1. throw an exception (my preferred), might not fit your library ideology
2. zombie / half constructed variable datum. I guess there'd have to be some kind of isValid() method as well in that case. 
3. make the buffer dynamic and allocate more when needed (ie. std::vector resize). this doesn't completely eliminate the possibility of an exception however.

**Comment by leif81** [comment]
Great analysis.

I think I like option 3 the most. And now that you said it, I remember there is a comment about this here:

https://github.com/open-dis/open-dis-cpp/blob/64200a2bf7de4041a050b2612bcd5502a836742a/cpp/DIS/VariableDatum.h#L7-L8

**Comment by dilavni** [comment]
You're correct. The developer had the right hunch.

I think the easiest solution so to go with std::vector<char> _variableDatums; with .reserve(STATIC_ARRAY_LENGTH) call in the constructor. That way there are no extra allocations unless the datum is larger than the 128 bytes mentioned.

Unfortunately my dev environment is air-gapped and the machine I'm writing this is not a development system. I'll have to submit this later from home when I have time. Or anyone can do it really :) It's just a few lines.

**Comment by dilavni** [comment]
also one has to remember to add the try{] catch block to the resize() call, if you want no throws. Then there is still the question of what to do with a zombie datum.

**Comment by leif81** [comment]
Fixed in PR #9
