### ISSUE TITLE
opendis6_export.h and opendis7_export.h missing

### ISSUE THREAD

**Issue by AJPerriello** [open-dis/open-dis-cpp#87]
nearly everything contains one of these headers files "opendis6_export.h" and "opendis7_export.h"
but those header files do not exist in src directories, or any other directory that I've looked into.
Won't compile without them. If you comment out the include, then there are even more errors, because that's where symbols had been defined.

**Comment by wadehunk** [comment]
@AJPerriello The export files are generated as part of the CMake build process depending on the desired build options (e.g. static/shared libs).

**Comment by AJPerriello** [comment]
> @AJPerriello The export files are generated as part of the CMake build process depending on the desired build options (e.g. static/shared libs).

good to know. thanks.
