### ISSUE TITLE
Alias targets set in config file cause cmake error when package is found more than once

### ISSUE THREAD

**Issue by a7marchesini** [open-dis/open-dis-cpp#90]
In my application, it's perfectly reasonable for, say, two different calls to ``find_dependency(OpenDIS)`` to be made, which in turn causes ``OpenDISConfig.cmake`` to be included twice. This is a bit of a problem, since then

```
## Add target aliases
add_library(OpenDIS::DIS6 ALIAS OpenDIS::OpenDIS6)
add_library(OpenDIS::DIS7 ALIAS OpenDIS::OpenDIS7)

## These are deprecated target names. All new references to the targets
## should utilize the new namespace wrapped version
add_library(OpenDIS6 ALIAS OpenDIS::OpenDIS6)
add_library(OpenDIS7 ALIAS OpenDIS::OpenDIS7)
```

gets run twice. The proposed fix is very straightforward, merely checking whether each target exists before creating it:

```
## Add target aliases
if (NOT TARGET OpenDIS::DIS6)
  add_library(OpenDIS::DIS6 ALIAS OpenDIS::OpenDIS6)
endif()
if (NOT TARGET OpenDIS::DIS7)
  add_library(OpenDIS::DIS7 ALIAS OpenDIS::OpenDIS7)
endif()

## These are deprecated target names. All new references to the targets
## should utilize the new namespace wrapped version
if (NOT TARGET OpenDIS6)
  add_library(OpenDIS6 ALIAS OpenDIS::OpenDIS6)
endif()
if (NOT TARGET OpenDIS7)
  add_library(OpenDIS7 ALIAS OpenDIS::OpenDIS7)
endif()
```

**Comment by leif81** [comment]
Thanks @a7marchesini 

Your suggestion makes sense to me. Could you submit the change as a pull request, it'll make it easier for the maintainers to review and merge.

**Comment by a7marchesini** [comment]
@leif81 I can make an MR if you'd like. However I tried pushing a branch and github rejected me. Do I need additional permissions for that?

**Comment by leif81** [comment]
You'll need to fork the project, try this

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by a7marchesini** [comment]
@leif81  Sorry for the delay. Fork created, branch made, pull request created (as noted by the UI above this message)
